---
all:
  hosts:
      host_monitoring:
        ansible_host: 192.168.56.201
        ansible_user: vagrant
        ansible_ssh_private_key_file: .vagrant/machines/srv1/virtualbox/private_key
      host_app:
        ansible_host: 192.168.56.202
        ansible_user: vagrant
        ansible_ssh_private_key_file: .vagrant/machines/srv2/virtualbox/private_key
  children:
    monitoring:
      hosts:
        host_monitoring:
    app:
      hosts:
        host_app: