# DOCKER PLAYBOOK
---
- hosts: "lab"
  become: true
  strategy: debug

  tasks:
  - name: Install deps
    ansible.builtin.apt:
      update_cache: true
      name:
        - ca-certificates
        - curl
      state: present

  - name: Add docker repo
    block:
    - name: Ensure keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add docker's gpg key
      ansible.builtin.command:
        cmd: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc"
      args:
        creates: "/etc/apt/keyrings/docker.asc"

    - name: Add apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

  - name: Install docker
    ansible.builtin.apt:
      update_cache: true
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      state: present

  - name: Add user to docker group
    ansible.builtin.user:
      name: "{{ ansible_user }}"
      groups: docker
      append: true
  
  - name: Start docker
    ansible.builtin.systemd:
      name: docker
      enabled: yes
      state: started
  
  - name: Run image
    community.docker.docker_container:
      name: app
      image: timurbabs/django
      ports:
        - "8000:8000"
      detach: true
      restart_policy: unless-stopped