# DOCKER PLAYBOOK
---
- hosts: lab
  become: true
  roles: 
    - docker
  tasks:
  - name: Run image
    community.docker.docker_container:
      name: app
      image: timurbabs/django
      ports:
        - "8000:8000"
      detach: true
      restart_policy: unless-stopped